---
    AWSTemplateFormatVersion: '2010-09-09'
    Description: Single machine in autoscaling 1:1 for simple test and simple purpose
    Parameters:
      VpcId:
        Type: AWS::EC2::VPC::Id
      SubnetId:
        Type: AWS::EC2::Subnet::Id
      InstanceType:
        Description: EC2 instance type
        Type: String
        Default: t2.micro
        ConstraintDescription: must be a valid EC2 instance type.
      KeyName:
        Description: The EC2 Key Pair to allow SSH access to the instances
        Type: AWS::EC2::KeyPair::KeyName
        ConstraintDescription: must be the name of an existing EC2 KeyPair.
    Resources:
      EC2Instance1:
        Type: AWS::EC2::Instance
        Properties:
            ImageId: ami-04b9e92b5572fa0d1
            KeyName: !Ref KeyName
            InstanceType: !Ref InstanceType
            SubnetId: !Ref SubnetId
            SecurityGroupIds:
            - !Ref InstanceSecurityGroup
            Tags:
              -
                Key: Name
                Value: web
              -
                Key: project
                Value: jrcms

      EC2Instance2:
        Type: AWS::EC2::Instance
        Properties:
            ImageId: ami-04b9e92b5572fa0d1
            KeyName: !Ref KeyName
            InstanceType: !Ref InstanceType
            SubnetId: !Ref SubnetId
            SecurityGroupIds:
            - !Ref InstanceSecurityGroup
            Tags:
              -
                Key: Name
                Value: web
              -
                Key: project
                Value: jrcms

      EC2Instance3:
        Type: AWS::EC2::Instance
        Properties:
            ImageId: ami-04b9e92b5572fa0d1
            KeyName: !Ref KeyName
            InstanceType: !Ref InstanceType
            SubnetId: !Ref SubnetId
            SecurityGroupIds:
            - !Ref InstanceSecurityGroup
            Tags:
              -
                Key: Name
                Value: redis
              -
                Key: project
                Value: jrcms

      InstanceSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
          VpcId:
            !Ref VpcId
          GroupDescription: Enable All traffic
          SecurityGroupIngress:
          - IpProtocol: "-1"
            CidrIp: 0.0.0.0/0

    Outputs:
      EC2Instance1:
        Description: web server 1
        Value: !GetAtt EC2Instance1.PublicIp
      EC2Instance2:
        Description: web server 2
        Value: !GetAtt EC2Instance2.PublicIp
      EC2Instance3:
        Description: redis server
        Value: !GetAtt EC2Instance3.PublicIp
