---
- name: Start jrcms container
  docker_container:
    name: jrcms
    image: davisliu/jrcms
    state: started
    ports:
      - "80:8080"
    env:
      REDIS_HOST: "{{ groups['tag_redis'][0] }}"
